### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-incubator/emsig#4]
[![Sig](https://pixabay.com/static/uploads/photo/2012/04/11/11/16/signature-27485_640.png)](https://pixabay.com/en/signature-icon-symbol-27485/)

**Comment by jhorstmann** [comment]
A bit large vertically, isn't it?

**Comment by whiskeysierra** [comment]
Just an idea. Since the background is white it should be easy to fill this up and scale down.

**Comment by jhorstmann** [comment]
Closing as we are moving to GHE
